### ISSUE TITLE
Clippy recommends updating to version 2.4-SNAPSHOT

### ISSUE THREAD

**Issue by easel** [softwaremill/scala-clippy#11]
As of this evening, clippy started insisting on updating to a snapshot version:

```
[error] New version of clippy plugin available: 0.2.4-SNAPSHOT. Please update!
[error] one error found
```

I'm assuming this isn't intentional?

In addition, these messages manage to break my build. Probably due to my build settings, but perhaps using an info message instead of an error would be less disruptive?

**Comment by kciesielski** [comment]
@easel Thanks for reporting this, I fixed it. Please `rm ~/.clippy/clippy.json.gz` and now the current version should be `0.2.3`.
By default this message is a warning, having `"-Xfatal-warnings"` in your `scalacOptions` makes it an error.

**Comment by easel** [comment]
Any chance to downgrade the warning to an info? Thanks for the fix!
