### ISSUE TITLE
A module is not authorized to depend on itself

### ISSUE THREAD

**Issue by joprice** [softwaremill/scala-clippy#15]
When I run `plugin/compile`, I get the error:

`a module is not authorized to depend on itself: com.softwaremill.clippy#plugin_2.11;0.2.5`

**Comment by kciesielski** [comment]
@joprice You have to remove clippy from your global sbt config (`~/.sbt/0.13/plugins/plugins.sbt` or wherever you do `addSbtPlugin`).

**Comment by joprice** [comment]
That makes sense. Thanks!
