### ISSUE TITLE
Allow overwriting/removing advice.

### ISSUE THREAD

**Issue by ShaneDelmore** [softwaremill/scala-clippy#19]
I added a bit of advice for Cats back when cats was on version 0.3.0.  They are now on version 0.6.0 and the advice is no longer correct. It would be great to have a way to either update the old advice, delete it, or have newer advice take priority.

**Comment by adamw** [comment]
If both the error message and advice is different, then I would simply add new advice - this sholdn't collide, right? 

If only the advice is different, there's currently a "suggest edit" link in the browse section to suggest changing advice. This is a manual process, which would be good to have it automated :)
