### ISSUE TITLE
2.12.0 build

### ISSUE THREAD

**Issue by marcelbuesing** [softwaremill/scala-clippy#24]
A 2.12.0 version would be great !

**Comment by adamw** [comment]
Should be there: http://repo1.maven.org/maven2/com/softwaremill/clippy/plugin_2.12/0.3.1/
Let me know if there are any problems :)

**Comment by marcelbuesing** [comment]
@adamw sorry I missed that. That must have been the fasted response I've seen to a Github issue. Thank you!
