### ISSUE TITLE
No Clippy advice for implicit ordering.

### ISSUE THREAD

**Issue by peterokagey** [softwaremill/scala-clippy#27]
I'm trying to add advice for:
`No implicit Ordering defined for java.time.LocalDateTime`

And it looks like it's not supported yet.

**Comment by ShaneDelmore** [comment]
I'll tackle this request.

**Comment by adamw** [comment]
Fixed in 0.3.3. Thanks @ShaneDelmore for the patch! @peterokagey could you try submitting advice now? :)

**Comment by peterokagey** [comment]
I pasted the original message reported (`No implicit Ordering defined for java.time.LocalDateTime`)

When I went to contribute at https://scala-clippy.org/, I saw this somewhat confusing message (which is missing `LocalDateTime`) :
`Implicit Ordering typeclass not found error: for type java.time`.

**Comment by peterokagey** [comment]
Thanks for the fix @ShaneDelmore!

**Comment by adamw** [comment]
Seems there is a difference in regexpes in JS and JVM :) Should be fixed now (0.3.4)
