### ISSUE TITLE
Exception because of clippy.xml

### ISSUE THREAD

**Issue by axaluss** [softwaremill/scala-clippy#5]
I gent an error when clippy tries to read the clippy file. 
`Exception when reading advices from https://www.scala-clippy.org/api/advices and storing to /home/nyxos/.clippy: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.`

The clippy.xml does not contain xml: 
`{"version":"0.2","advices":[{"id":694836570716508160,"error":{"type":"typeMismatch","found":"akka\\.http\\.scaladsl\\.server\\.StandardRoute","required":"akka\\.stream\\.scaladsl\\.Flow\\[akka\\.http\\.scaladsl\\.model\\.HttpRequest,akka\\.http\\.scaladsl\\.model\\.HttpResponse,Any\\]"}.....`

[clippy.xml.txt](https://github.com/softwaremill/scala-clippy/files/127182/clippy.xml.txt)

**Comment by kciesielski** [comment]
@axaluss Clippy changed internal format from XML to JSON in version 0.2. Please update your dependency.
