### ISSUE TITLE
Version 0.5.3 is not available for Scala 2.11

### ISSUE THREAD

**Issue by jqno** [softwaremill/scala-clippy#56]
Clippy is awesome!

I've tried updating Clippy to version 0.5.3, but it keeps saying that it can't resolve `com.softwaremill.clippy#plugin_2.11;0.5.3`.

When I [search Maven](http://search.maven.org/#search%7Cga%7C1%7Cclippy), it confirms that while there are 0.5.3 artifacts for Scala 2.10 and 2.12, the most recent one for 2.11 is 0.5.2.

Given that there's a 0.5.3 artifact for Scala 2.10, I'm guessing that this is not intentional :).

**Comment by adamw** [comment]
Not sure how that happened - should be there in about 15 minutes :)

**Comment by jqno** [comment]
Excellent! And thanks for the quick response :).

**Comment by jqno** [comment]
It's already there, I just did a successful compile with 0.5.3. Thanks!

**Comment by adamw** [comment]
Great :)
