### ISSUE TITLE
`DelegatingReporter` breaks macro info messages

### ISSUE THREAD

**Issue by fwbrasil** [softwaremill/scala-clippy#6]
Reported by @ShaneDelmore when trying to use [Quill](http://getquill.io):

https://gist.github.com/ShaneDelmore/3932364464583ae322c7

Is the method not implemented by design?

**Comment by kciesielski** [comment]
Could elaborate a bit more? How exactly are you trying to use clippy with Quill?

**Comment by ShaneDelmore** [comment]
I just added this line to my build.sbt and it caused the error.  Removing the line fixed it.
addSbtPlugin("com.softwaremill.clippy" % "plugin-sbt" % "latest.integration")

**Comment by adamw** [comment]
Hmm I though that this wasn't called directly. Unfortunately that method (`info0`) is `protected` and the one that calls it in that particular case (`info`) is `final`, so neither can be delegated. Maybe we can work around by looking at the severity and calling the right method, but that doesn't sound that great. I'll take a look early next week

**Comment by adamw** [comment]
Can you try 0.2.1? I hope this will fix the problem - let me know if something is still wrong :)

**Comment by ShaneDelmore** [comment]
Works great!  Thank you.
